### PR TITLE
Fixed 7z2john.py to 7z2john.pl

### PR DESCRIPTION
**Pull request by mda01**
Fixing this issue:
https://github.com/openwall/johnny/issues/127

### CODE REVIEW

**Comment by solardiz** [comment]
Thanks! BTW, you could have written "Fixes #127" to have merging this PR automatically close the issue.

How about you fix #123 next?

**Comment by eli-b** [comment]
Would you consider releasing a minor version that includes this fix?

**Comment by solardiz** [comment]
@eli-b Do you perhaps mean new binary builds (something you can readily use) more than a release (a technicality)? For just this fix alone, probably no - there are many more things we need to update, including similar ones (there are more `*2john` tools by now than Johnny is aware of). However, we do need to start doing binary builds again, which would also encourage people to be improving the source code. Maybe we need automated binary builds for a few systems made in the cloud, maybe like @claudioandre-br set up for the main JtR project. @shinnok @AlekseyCherepanov what do you guys think of this? Any volunteers to set this up?

As to releases, I think producing a JtR 2.0 release based on current bleeding-jumbo is a higher priority, then we should make a Johnny release matching it, and consider merging Johnny into the main JtR tree after 2.0. Then just one automated builds setup will cover all.

**Comment by eli-b** [comment]
I guess I meant both a version release and the binary builds that would go with it. Otherwise, I could have tried to build johnny myself from the head of master.

Automated binary builds sound useful.

**Comment by shinnok** [comment]
Hi, updating Johnny at this point is a task of its own, since everything is at least 5 years old. @eli-b, if possible, I would recommend you not wait for a release anytime soon.

@solardiz I'm a bit out of the loop, is JtR 2.0 imminent? If so, maybe I can read up a little on what's changed in the meantime and consider if it's worth updating Johnny solely or just wait and see what would exactly be needed for inclusion into main/Jumbo.

**Comment by solardiz** [comment]
@shinnok I think the current jumbo tree is close to what we could release as JtR 2.0 - just need some documentation updates, and to actually make the release (including builds, testing, announcements, etc.) - however, I am busy with other projects, so no, the release is not imminent. Yet you can reasonably update Johnny now to reflect new `*2john` tools and new/changed `john` options. Thanks!

**Pull request merged**
