### PR TITLE
JtR validator

### PR DESCRIPTION
**Pull request by math07**
It include #68

### CODE REVIEW

**Comment by math07** [comment]
Tell me what you think of it

**Comment by frank-dittrich** [comment]
I guess for core you'll just grab whatever follows the "version" string in the usage output.

For jumbo, you can also use the first lines of `./john --list=build-info` output:
``` 
Version: 1.8.0.6-jumbo-1-702-g8c02014
Build: linux-gnu 64-bit AVX-ac OMP
```

The `git describe --tags --dirty=+` output will not be used for release builds, just for normal autoconf builds inside a git repository.

If you download the current commit's tarball and extract it, you'll currently get a version string `1.8.0.6-jumbo-1-bleeding`, and a proper jumbo version once anew release is created.

**Comment by magnumripper** [comment]
The first line of the usage blob (eg. ./john|head -1) will always work. I see no reason for you to use Jumbo's --list=build-info

**Comment by math07** [comment]
@shinnok I adressed your 3 comments in a05cfe0 and I'll merge this now to do the planned GSOC release.

**Pull request merged**
