### PR TITLE
*2john support

### PR DESCRIPTION
**Pull request by math07**
It's a WIP.

### CODE REVIEW

**Comment by math07** [comment]
@shinnok I managed to make quite some progress on the intuitive UI that could compete against command line that I talked yesterday on the list. For example, you can build and test the use case selecte unafs, after that unshadow, after that dmg formats. You can see the UI adapting. There are still some important things that aren't done but I think I can have a working version today. If you like the UI, the design and the way to add new formats(in buildFormatUI() method) which we could easily adapt if we got scripts with more complicated parameters in the future, I can continue or abandon this task.

**Comment by shinnok** [comment]
I've taken this for a spin and I like what I'm seeing. You can proceed with it.

A suggestion, the input format list should be a QComboBox instead of many radioboxes. The latter doesn't scale nicely.

**Comment by math07** [comment]
I like the radio buttons because, from a usability point of view, you can see all formats at once really fast and they are always shown. However, you're right about the fact that if we got 200 formats it's gonna take lot of room. For now I think we have enough room but I can change It now to be future-proof.

**Comment by math07** [comment]
As I said on the list, we'll have some issues with error handling for scripts that don't follow the bare minimum, but we can't do anything about that. 

I think that some scripts like sshng return SUCCESS and print errors on stdout. This makes it hard for CLI like Johnny. I think that all scripts should print errors to stderr and when an error happens like file not found, not a valid file etc.. return 1. I've seen several 2*john script doing that correctly.

The worst that can happens is that a bad file will be opened in the table view instead of us preventing it and displaying stderr :

**Comment by math07** [comment]
In you have other comments regarding this, please tell me now I have plans on doing a manual code review + some final tests + merge this sunday.

**Comment by shinnok** [comment]
I'm taking another look now.

**Comment by shinnok** [comment]
Good work with this feature. I'm quite pleased with how it turned out in such a short amount of time.

I have some fixes and adjustments published to my branch:
https://github.com/shinnok/johnny/commits/shinnok-xxx2john

You can merge it into yours or after we merge the PR back to main. You can make the merges when you consider fit.

**Pull request merged**
