### PR TITLE
Add new tooltip in the password table

### PR DESCRIPTION
**Pull request by math07**

### CODE REVIEW

**Comment by shinnok** [comment]
The tooltip should have been set on the QCheckbox in the table.

**Comment by math07** [comment]
OK I'll change it

**Comment by math07** [comment]
The reason why I didn't do it in the first place is that I'm not sure if we have public access to the QCheckBox* itself. They seems to be encapsulated into a bigger object when we create them Model based  (via the data() method and  Qt::Checked role) . I tried to findChildren<QCheckBox*> of the table view and it returned 0 and I don't see other access method for them. 

On the other hand to set a tooltip for the each row of the user column would be super easy with the Qt::Tooltip data role. However, not sure that's exactly what you want ...

**Comment by shinnok** [comment]
Ok I understand. Let's leave as is then.

**Pull request merged**
