### PR TITLE
Adapt hashTypeChecker to JohnHandler interface

### PR DESCRIPTION
**Pull request by math07**

### CODE REVIEW

**Comment by math07** [comment]
> Don't pass the path to john like that. Set it from outside of this method in preparation for multi-session.
I started working on multi-session, but this message makes me kind of worried about my understanding of the task. I gathered previous information from thread in http://www.openwall.com/lists/john-dev/2015/06/02/26 and understand that it's something like that that you want and not running multiple john instance at the same time right ?
johnny
Sessions are saved automatically and written in the history. If date time isn't enough, we could write the name of file in tooltip of the menu action.

**Comment by shinnok** [comment]
@math07 Let's not discuss a totally unrelated task in this issue's thread. If you don't have a PR ready at least create a new Issue with label "Feature" and bring the discussion there.

**Comment by math07** [comment]
> @math07 Let's not discuss a totally unrelated task in this issue's thread. If you don't have a PR ready at least create a new Issue with label "Feature" and bring the discussion there.

I know it's not the place to talk about this but I'm trying to get your attention, you don't answer my questions regarding this on the list which are blocking way more than this PR. So since you're on github, I try to get your attention on this. :)

**Comment by shinnok** [comment]
@math07 I understand, but you have been cautioned that in this period I'm going to be a bit overloaded. I'm going to go through the mail list backlogs in the next hour.

Still, create that new Issue and bring the comment with the screenshot there.

Thanks.

**Comment by math07** [comment]
Yes, #19 and #20 

> @math07 I understand, but you have been cautioned that in this period I'm going to be a bit overloaded. I'm going to go through the mail list backlogs in the next hour.

Yeah I understand. If you don't have time, it's okay. If I finish the task and it's not the requirements that you had in mind, I'll just adapt to it. But I want to tell you that if you have some minutes, it'll pay a lot more to spend it on clarifying the multi-session task than commenting PR #19, #20 . Thanks !

**Comment by math07** [comment]
Changes done :)

**Comment by shinnok** [comment]
Merged. Thanks for the good work!

**Pull request merged**
